### ISSUE TITLE
Is there any way to compile qt platform statically into the executable on Windows?

### ISSUE THREAD

**Issue by caiwan** [kusma/rocket#10]
Since QT is a pain on windows, I'm continuosly having problem with running the app. [Following this](https://wiki.qt.io/Deploy_an_Application_on_Windows). I can't deploy the executable properly to run standalone, unless I'm not install the entrire QT platform. I've copied the dlls from the binary directory of QT, including the plafrom plugins. I've tried several folder structure for them (`./`, `./plugins`, `./plugins/platforms/` `./platforms`, `./platforms/plugins`, ...) 
I assume there is a method to compile these into the exe, and not using and dlls, but I couldn't achieve these. E.g. [this one](https://wiki.qt.io/Build_Standalone_Qt_Application_for_Windows). 

Do you have any suggestions?

**Comment by kusma** [comment]
I had troubles getting this to work myself in Qt5, so last time I needed to package it up I simply used Qt4 where it was a breeze. Dunno if that works for you, though :/

**Comment by caiwan** [comment]
Thank you, I could'nt find a way to make it work without the entire QT SDK.
