### ISSUE TITLE
problems compiling example in vs2010

### ISSUE THREAD

**Issue by nabulator** [kusma/rocket#17]
>example_bass.obj : error LNK2019: unresolved external symbol _sync_destroy_device referenced in function _main
>example_bass.obj : error LNK2019: unresolved external symbol _sync_get_val referenced in function _main
>example_bass.obj : error LNK2019: unresolved external symbol _sync_get_track referenced in function _main
>example_bass.obj : error LNK2019: unresolved external symbol _sync_create_device referenced in function _main
>C:\Users\orange\Documents\Modern\rocket\Debug\example_bass.exe : fatal error LNK1120: 4 unresolved externals

Not sure what's going on here. I compiled the editor without much problem.

**Comment by kusma** [comment]
Unfortunately, I don't have VS2010 installed anywhere, and Microsoft is making it harder and harder to install older VS versions, but I can give it a go a bit later.

How did you get VS2010 project files? Did you upgrade the VS2008 ones? I recently changed these without testing much on VS2008, so it could be a problem I introduced without noticing then...

**Comment by nabulator** [comment]
I decided to upgrade to vs express 2013 and the error is gone. Instead I'm getting an error that cannot find any of the qt dll's (qt5core,dll, qt5wxwidgets.dlll, qtgui.dll, etc).

**Comment by kusma** [comment]
You need to either copy the Qt dlls into your build-directory (`windeployqt` can do this for you, this is what I do when building on [appveyor](https://ci.appveyor.com/project/kusma/rocket/branch/master)), or set your Qt bin-dir in `%PATH%` (this I what I do when debugging)...

**Comment by kusma** [comment]
By the way, if you don't want to build the editor you can find pre-built binaries on Appveyor. [Here's](https://ci.appveyor.com/project/kusma/rocket/build/27/job/sma1v045jsst6j37/artifacts) the most recent build from master.
